pred_user:
    resource: "@PredUserBundle/Resources/config/routing.yml"
    prefix:   /

pred_demande:
    resource: "@PredDemandeBundle/Resources/config/routing.yml"
    prefix:   /
pred_demande_etablissement:
        resource: "@PredDemandeBundle/Resources/config/routing/etablissement.yml"
        prefix:   /etablissement

pred_demande_diplome:
        resource: "@PredDemandeBundle/Resources/config/routing/diplome.yml"
        prefix:   /diplome

pred_demande_evaluateur:
        resource: "@PredDemandeBundle/Resources/config/routing/evaluateur.yml"
        prefix:   /evaluateur

#school_login:
#    pattern: school_login
#    defaults: { _controller: PredDemandeBundle:Security:login }

#login_check:
#    pattern: /etablissement/login_check

#logout:
#    pattern: /etablissement/logout


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /user

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile