security:
    encoders:
        Pred\DemandeBundle\Entity\Etablissement:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        entity_etablissement:
            entity:
                class: Pred\DemandeBundle\Entity\Etablissement

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        etablissement_firewall:
            pattern:  ^/etablissement
            anonymous: false
            provider: entity_etablissement
            form_login:
                check_path: /etablissement/login_check
                login_path: school_login
                default_target_path: /pred
            logout:
                path: logout
                target: /pred


            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #school_area:
        #       path: /etablissement/.*
        #       roles: ROLE_USER