<?php

namespace Pred\DemandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluateurRepository extends EntityRepository
{
}
