evaluateur:
    pattern:  /
    defaults: { _controller: "PredDemandeBundle:Evaluateur:index" }

evaluateur_show:
    pattern:  /{id}/show
    defaults: { _controller: "PredDemandeBundle:Evaluateur:show" }

evaluateur_new:
    pattern:  /new
    defaults: { _controller: "PredDemandeBundle:Evaluateur:new" }

evaluateur_create:
    pattern:  /create
    defaults: { _controller: "PredDemandeBundle:Evaluateur:create" }
    requirements: { _method: post }

evaluateur_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PredDemandeBundle:Evaluateur:edit" }

evaluateur_update:
    pattern:  /{id}/update
    defaults: { _controller: "PredDemandeBundle:Evaluateur:update" }
    requirements: { _method: post|put }

evaluateur_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PredDemandeBundle:Evaluateur:delete" }
    requirements: { _method: post|delete }

evaluateur_liste:
    pattern:  /liste
    defaults: { _controller: "PredDemandeBundle:Evaluateur:liste" }